jwt:
  secret: "toto"

server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_managment
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database: mysql
#  mvc:
#    throw-exception-if-no-handler-found: true
##  resources:
##    add-mappings: false
#  web:
#    resources:
#      add-mappings: false
#  main:
#    allow-circular-references: true

